# Generated by Django 3.1 on 2020-08-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
