# Generated by Django 3.1 on 2020-08-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200806_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
