# Generated by Django 3.1 on 2020-08-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_useractivity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserActivity',
            new_name='Activity',
        ),
    ]
